name: wesense
favicon: null
layout_spectrum: 0.23384
typography_spectrum: 0.58001
title: 'we sense - tech & art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dcdcdc'
    - '#262626'
    - '#6f6f6f'
  brandStrength: 1
  lightness: 0.9576977519318461
  saturation: 0.027336770202964544
  rhythmicContrast: 0.6405598232522607
purpose: []
